export const Colors = {
  primary: '#535f6f',
  onPrimary: '#ffffff',
  secondary: '#735a36',
  onSecondary: '#ffffff',
  secondaryContainer: '#fddaac',
  onSecondaryContainer: '#785e39',
  tertiary: '#51606b',
  onTertiary: '#ffffff',
  tertiaryContainer: '#a0b0bc',
  surface: '#fdf9f1',
  onSurface: '#1c1c17',
  surfaceVariant: '#e6e2da',
  onSurfaceVariant: '#4e453b',
  surfaceContainerLow: '#f7f3eb',
  surfaceContainer: '#f1ede5',
  surfaceContainerHigh: '#ece8e0',
  surfaceContainerHighest: '#e6e2da',
  surfaceContainerLowest: '#ffffff',
  error: '#ba1a1a',
  outline: '#7f766a',
  primaryContainer: '#a2afc1',
  onPrimaryContainer: '#364251',
  secondaryFixedDim: '#e2c195',
} as const;